---
- name: Create server init script
  template:
    src: server.init.j2
    dest: /etc/init.d/{{server_name}}
    mode: 0755
  vars:
    pidfile: shaco.pid
    configfile: config_game

- name: Create state init script
  template:
    src: server.init.j2
    dest: /etc/init.d/{{state_name}}
    mode: 0755
  vars:
    pidfile: shaco.state.pid
    configfile: config_state
