---
- name: set ulimit core
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: core
    value: "{{sys_core}}"

- name: set ulimit nofile
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: "{{sys_nofile}}"

- name: set sysctl SOMAXCONN
  sysctl:
    name: "net.core.somaxconn"
    value: "{{sys_backlog}}"
