---

- name: restart shadowsocks
  service: name=shadowsocks state=restarted

- name: save iptables 
#  service: name=iptables state=save
  command: /usr/sbin/iptables-save

- name: restart iptables
  service: name=iptables state=restarted
