---
- name: Logrotate install qzserver
  include_role: name=logrotate
  vars: 
    logrotate_scripts:
      - name: "{{server_name}}"
        path: "{{server_logdir}}/shaco.log"
        options:
          - daily
          - dateext
          - rotate 10
          - missingok
          - notifempty
            #          - compress
            #- delaycompress
        scripts:
            postrotate: "[ -s {{server_pidfile}} ] && kill -USR1 `cat {{server_pidfile}}`"
  when: inventory_hostname in groups["gameserver"]

- name: Logrotate install qzstate
  include_role: name=logrotate
  vars: 
    logrotate_scripts:
      - name: "{{state_name}}"
        path: "{{server_logdir}}/shaco.log.state"
        options:
          - daily
          - dateext
          - rotate 10
          - missingok
          - notifempty
            #- compress
            #- delaycompress
        scripts:
            postrotate: "[ -s {{state_pidfile}} ] && kill -USR1 `cat {{state_pidfile}}`"
  when: inventory_hostname in groups["gameserver"]

- name: Logrotate install qzbilling
  include_role: name=logrotate
  vars: 
    logrotate_scripts:
      - name: "{{billing_name}}"
        path: "{{server_logdir}}/shaco.log.billing"
        options:
          - daily
          - dateext
          - rotate 10
          - missingok
          - notifempty
            #- compress
            #- delaycompress
        scripts:
            postrotate: "[ -s {{billing_pidfile}} ] && kill -USR1 `cat {{billing_pidfile}}`"
  when: inventory_hostname in groups["billingserver"]
