---
- name: Logrotate install qzserver
  include_role: name=logrotate
  vars: 
    logrotate_scripts:
      - name: qzserver_{{gateport}}
        path: "{{server_logdir}}/shaco.log"
        options:
          - daily
          - dateext
          - rotate 10
          - missingok
          - notifempty
          - compress
          - delaycompress
        scripts:
            postrotate: "[ -s {{qzserver_pidfile}} ] && kill -USR1 `cat {{qzserver_pidfile}}`"

- name: Logrotate install qzstate
  include_role: name=logrotate
  vars: 
    logrotate_scripts:
      - name: qzstate_{{gateport}}
        path: "{{server_logdir}}/shaco.log.state"
        options:
          - daily
          - dateext
          - rotate 10
          - missingok
          - notifempty
          - compress
          - delaycompress
        scripts:
            postrotate: "[ -s {{qzstate_pidfile}} ] && kill -USR1 `cat {{qzstate_pidfile}}`"
