---
- name: Qz gameserver
  hosts: gameserver
  roles: 
    - role: mysql
      become: true
      become_method: su
      tags: [ 'init', 'dev' ]

    - role: redis
      become: true
      become_method: su
      tags: [ 'init', 'dev' ]

    - role: qzserver
