---
# create ssh user and copy ssh key

- name: create ssh user 
  user: 
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ sshuser }}"

- name: copy ssh key
  authorized_key: 
    user: "{{ item.0.name}}"
    key: "{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{ sshuser }}"
    - authorized

  #- set_fact: pubkey_list="{{ lookup('file', item.1) }}"
  #  register: "{{item.0.name}}"
  #  with_subelements:
  #    - "{{sshuser}}"
  #    - authorized
  #
  #- debug: msg="{{item.0.name}}"
  #  with_subelements:
  #    - "{{sshuser}}"
  #    - authorized
  #
  #- name: copy ssh key
  #  authorized_key: 
  #    user: "{{ item.name}}"
  #    key: "{{ item.authorized | join('\n') | string }}"
  #  with_flattened:
  #    - "{{sshuser}}"
